# -*- coding: utf-8 -*-
"""Copy of deploymodel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TH0aYk81VA987ANqCjkKJ08xgewDCHsr
"""

import streamlit as st
import tensorflow as tf
from tensorflow.keras.utils import img_to_array
from keras.models import load_model
from PIL import Image
import numpy as np

@st.cache(allow_output_mutation=True)
def load_model():
    model = tf.keras.models.load_model('saved_fashion_model.h5')
    return model

model = load_model()

st.write("# Fashion Outfit Classification (Santos, Jullian York G., CPE019-CPE32S5)")

file = st.file_uploader("Choose any fashion-related photo from your computer", type=["jpg", "png"])

def import_and_predict(image_data, model):
    img = Image.open(image_data).resize((28, 28))
    img = img_to_array(img)
    img = img[:,:,0]
    img = img.reshape(1, 28, 28, 1)
    img = img.astype('float32')
    img = img / 255.0
    result = np.argmax(model.predict(img), axis=1)
    return result

if file is None:
    st.text("Please upload an image file")
else:
    image = Image.open(file).resize((224, 224))
    st.image(image, use_column_width=True)
    result = import_and_predict(file, model)
    labels = {
        0: 'T-shirt/top',
        1: 'Trouser',
        2: 'Pullover',
        3: 'Dress',
        4: 'Coat',
        5: 'Sandal',
        6: 'Shirt',
        7: 'Sneaker',
        8: 'Bag',
        9: 'Ankle boot'
    }
    string = "OUTPUT: " + labels[result[0]]
    st.success(string)